### ISSUE TITLE
Expy-Kit Not working with Blender 3.1

### ISSUE THREAD

**Issue by YTMPRo** [pKrime/Expy-Kit#14]
I get this error every time I try and use Expy-Kit with blender 3.1. 

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Expy-Kit-main\operators.py", line 538, in execute
    metarig = next(ob for ob in bpy.data.objects if ob.type == 'ARMATURE' and ob.data.rigify_target_rig == src_object)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Expy-Kit-main\operators.py", line 546, in execute
    metarig.data.rigify_rig_basename = src_object.name
AttributeError: 'Armature' object has no attribute 'rigify_rig_basename'

**Comment by YTMPRo** [comment]
I just made sure, Yes, rigify is enabled and up to date in the add on preferences.

**Comment by pKrime** [comment]
Hi, did you download the latest snapshot from the Github project (Big Green Button). If I'm not wrong that error has been fixed: which version of Expy Kit are you using?

p.

**Comment by YTMPRo** [comment]
I'm using version 0.2.0 ill redownload it now.

**Comment by YTMPRo** [comment]
I redownloaded and reinstalled plugin and I'm still getting the same issue. going to try and restart my computer.

**Comment by pKrime** [comment]
Hi, last version is 0.2.1. Perhaps something went wrong with install/removal. You might also try to remove Expy Kit completely before trying again

**Comment by YTMPRo** [comment]
Awesome that worked! Thank you!

**Comment by pKrime** [comment]
Closing this, cheers! :)
